xcopy /y /f "C:/dev/IwEngine/IwEngine/bin/Debug.windows.x86_64/*.dll" "C:/dev/IwEngine/_export/bin/Debug.windows.x86_64/"
xcopy /y /f "C:/dev/IwEngine/IwEngine/lib/Debug.windows.x86_64/*.lib" "C:/dev/IwEngine/_export/lib/Debug.windows.x86_64/"
xcopy /y /f /e "C:/dev/IwEngine/IwEngine/include/*" "C:/dev/IwEngine/_export/include/"
xcopy /y /f /e "C:/dev/IwEngine/IwTools/include/*" "C:/dev/IwEngine/_export/include/"
xcopy /y /f /e "C:/dev/IwEngine/IwEngine/extern/imgui/include/*" "C:/dev/IwEngine/_export/include/"
xcopy /y /f /e "C:/dev/IwEngine/IwEngine/extern/fmod/include/*" "C:/dev/IwEngine/_export/include/"
xcopy /y /f    "C:/dev/IwEngine/IwEngine/extern/json/*.h" "C:/dev/IwEngine/_export/include/json/"
xcopy /y /f "C:/dev/IwEngine/IwEngine/extern/imgui/lib/Debug.windows.x86_64/ImGui.lib" "C:/dev/IwEngine/_export/lib/Debug.windows.x86_64"